resources:
- name: my-resource
  type: git
  source:
    uri: https://github.com/L-Sakurai/master.git
    branch: master

jobs:
- name: read-my-resource
  public: true
  plan:
  - get: my-resource
  - task: my-task
    file: my-resource/concourse/concourse_opt/resource-repo/my-prc/myCustomTask.yml
    
